import assert from 'node:assert/strict';
import { demoItems } from '../js/demo.js';
import { planTrip, shoppingSuggestions, wardrobeStats } from '../js/planning.js';
import { weatherFromTemp } from '../js/engine.js';
const items = demoItems(1);
const byId = new Map(items.map(i=>[i.id,i]));
const dayList = Array.from({length:5},(_,i)=>({date:'2026-10-0'+(i+1), occasion: i===2?'going-out':'everyday', weather: {...weatherFromTemp(14), season:'autumn'}}));
let t=performance.now();
const trip = planTrip(items, { dayList, style: 'casual' });
console.log('trip ms', (performance.now()-t).toFixed(0), 'packing', trip.packing.length, trip.packing.map(id=>byId.get(id).name));
assert.ok(trip.series.every(s=>s.items));
assert.ok(trip.packing.length < 14);
t=performance.now();
const shop = shoppingSuggestions(items);
console.log('shop ms', (performance.now()-t).toFixed(0), 'orphans', shop.orphans.length);
for (const s of shop.suggestions) console.log(' ', s.score, s.colorName, s.subtype, '|', s.reasons.join(' '));
const small = items.filter(i => ['tshirt','trousers'].includes(i.category)).slice(0,6);
const s2 = shoppingSuggestions(small);
console.log('small wardrobe:', s2.suggestions.map(s=>s.colorName+' '+s.subtype).join(', '));
const st = wardrobeStats({items, outfits: [], wears: [{date:'2026-09-20', itemIds:['demo-0','demo-e','demo-m']},{date:'2026-09-21', itemIds:['demo-0','demo-f','demo-m']}]});
console.log(st.totals, st.most.map(m=>m.item.name+':'+m.count), st.topPairs);
console.log('OK');
